# Generated by Django 3.2.5 on 2021-08-05 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposition_RF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.date(2021, 8, 6), verbose_name='Date')),
                ('user', models.CharField(max_length=20, verbose_name='User')),
                ('material', models.CharField(choices=[('SiO2', 'SiO2'), ('Si', 'Si')], default='SiO2', max_length=10, verbose_name='Material')),
                ('power', models.IntegerField(default=250, verbose_name='Power (W)')),
                ('pressure', models.FloatField(default=0.84, verbose_name='Pressure (mTorr)')),
                ('mfc_flow', models.FloatField(default=10.0, verbose_name='MFC flow (sccm)')),
                ('deposition_time', models.DurationField(default=datetime.timedelta(seconds=1800), verbose_name='Deposition time')),
                ('thickness', models.FloatField(verbose_name='Thickness (nm)')),
                ('comment', models.CharField(max_length=256, verbose_name=' Comment')),
            ],
        ),
    ]
