# Generated by Django 3.2.5 on 2021-08-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sputter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposition_rf',
            name='thickness',
            field=models.FloatField(blank=True, null=True, verbose_name='Thickness (nm)'),
        ),
    ]
