# Generated by Django 3.2.5 on 2021-08-06 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sputter', '0002_alter_deposition_rf_thickness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposition_rf',
            name='deposition_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=1800), null=True, verbose_name='Deposition time'),
        ),
        migrations.AlterField(
            model_name='deposition_rf',
            name='mfc_flow',
            field=models.FloatField(blank=True, default=10.0, null=True, verbose_name='MFC flow (sccm)'),
        ),
        migrations.AlterField(
            model_name='deposition_rf',
            name='power',
            field=models.IntegerField(blank=True, default=250, null=True, verbose_name='Power (W)'),
        ),
        migrations.AlterField(
            model_name='deposition_rf',
            name='pressure',
            field=models.FloatField(blank=True, default=0.84, null=True, verbose_name='Pressure (mTorr)'),
        ),
    ]
